name: Test Bun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest # Linux base image
    steps:
      - uses: actions/checkout@v3 # Checkout repo
      - uses: oven-sh/setup-bun@v1 # Setup bun
        with:
          bun-version: latest
      - run: bun install
      - run: bun test
